INFO	2021-11-05 17:55:06,146	[basepage.py:32]	打开网页https://www.imymac.com/sitemap/
INFO	2021-11-05 17:55:07,301	[basepage.py:96]	获取到文本：How To Clear Search History On Chrome, Safari, Firefox
INFO	2021-11-05 17:55:07,317	[basepage.py:96]	获取到文本：How To Clear Search History On Chrome, Safari, Firefox
INFO	2021-11-05 17:55:07,333	[basepage.py:96]	获取到文本：How To Clear Search History On Chrome, Safari, Firefox
WARNING	2021-11-05 17:55:16,810	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A14B52D670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d78e90dbd9913cba749f16f9c14c45ef/timeouts
WARNING	2021-11-05 17:55:18,842	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A14B630C40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d78e90dbd9913cba749f16f9c14c45ef/timeouts
WARNING	2021-11-05 17:55:20,875	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A14B630910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d78e90dbd9913cba749f16f9c14c45ef/timeouts
WARNING	2021-11-05 17:55:25,096	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A14B9CFBB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d78e90dbd9913cba749f16f9c14c45ef
WARNING	2021-11-05 17:55:27,121	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A14B899EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d78e90dbd9913cba749f16f9c14c45ef
WARNING	2021-11-05 17:55:29,149	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A14B899A00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d78e90dbd9913cba749f16f9c14c45ef
