INFO	2021-11-05 17:54:09,010	[basepage.py:32]	打开网页https://www.imymac.com/sitemap/
INFO	2021-11-05 17:54:09,878	[basepage.py:96]	获取到文本：Convert WMA to MP3 Online for Free with High Quality
INFO	2021-11-05 17:54:09,905	[basepage.py:96]	获取到文本：Convert WMA to MP3 Online for Free with High Quality
INFO	2021-11-05 17:54:09,926	[basepage.py:96]	获取到文本：Convert WMA to MP3 Online for Free with High Quality
WARNING	2021-11-05 17:54:19,778	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70AD0D670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2/timeouts
WARNING	2021-11-05 17:54:21,819	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70AD61E20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2/timeouts
WARNING	2021-11-05 17:54:23,855	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70AD61730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2/timeouts
WARNING	2021-11-05 17:54:28,054	[connectionpool.py:780]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70B118520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2
WARNING	2021-11-05 17:54:30,084	[connectionpool.py:780]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70B0E0B20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2
WARNING	2021-11-05 17:54:32,102	[connectionpool.py:780]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E70B0E0A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/98228426e4bf49983f02973fe152a4b2
